version: '3.8' # Docker Compose 파일 형식 버전, 3.8은 최신 기능을 지원하는 안정적인 버전

services: # 실행할 컨테이너 서비스 정의 시작
  {{SERVICE_NAME}}: # 서비스 이름 변수, 새 서비스 생성 시 실제 서비스명으로 치환됨
    image: {{DOCKER_REGISTRY}}/{{SERVICE_NAME}}:{{IMAGE_TAG}} # 사용할 도커 이미지, 레지스트리/서비스명:태그 형식
    container_name: {{SERVICE_NAME}}-dev # 컨테이너 이름 지정, 서비스 식별 및 관리용
    ports: # 포트 매핑 설정 시작
      - '{{SERVICE_PORT}}:{{SERVICE_PORT}}' # 호스트:컨테이너 포트 매핑, 동일 포트 사용
    environment: # 컨테이너 내부 환경변수 설정 시작
      - NODE_ENV=development # Node.js 환경을 개발 모드로 설정
      - TURBO_TEAM=${TURBO_TEAM} # Turborepo 팀 식별자, 호스트 환경변수에서 주입
      - TURBO_TOKEN=${TURBO_TOKEN} # Turborepo 접근 토큰, 호스트 환경변수에서 주입
    restart: always # 컨테이너 종료 시 항상 재시작하도록 설정
    logging: # 로깅 설정 시작
      driver: "awslogs" # AWS CloudWatch Logs를 로그 드라이버로 사용
      options: # 로깅 옵션 상세 설정
        awslogs-group: "/ecs/{{SERVICE_NAME}}-logs" # CloudWatch 로그 그룹 이름
        awslogs-region: "ap-northeast-2" # 로그를 저장할 AWS 리전
        awslogs-create-group: "true" # 로그 그룹이 없을 경우 자동 생성
        awslogs-stream-prefix: "{{SERVICE_NAME}}" # 로그 스트림 접두사, 서비스 이름으로 설정 